name: vje_library
channels:
  - defaults
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - icu=75.1
  - libcxx=21.1.2
  - libffi=3.4.6
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libmpdec=4.0.0
  - libsqlite=3.50.4
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.3
  - pip=25.2
  - python=3.13.7
  - python_abi=3.13
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.50.4
  - tk=8.6.15
  - wheel=0.45.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zlib=1.3.1
  - pip:
      - cachetools==6.2.0
      - certifi==2025.8.3
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - contourpy==1.3.3
      - cryptography==43.0.3
      - cycler==0.12.1
      - fonttools==4.60.1
      - google-api-core==2.25.1
      - google-api-python-client==2.183.0
      - google-auth==2.41.0
      - google-auth-httplib2==0.2.0
      - googleapis-common-protos==1.70.0
      - httplib2==0.31.0
      - idna==3.10
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.6
      - numpy==2.3.3
      - oauth2client==4.1.3
      - oauthlib==3.3.1
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.3.0
      - proto-plus==1.26.1
      - protobuf==6.32.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pydrive2==1.21.3
      - pyopenssl==24.2.1
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - seaborn==0.13.2
      - six==1.17.0
      - tabulate==0.9.0
      - tzdata==2025.2
      - uritemplate==4.2.0
      - urllib3==2.5.0
      - wcwidth==0.2.14
